/**
 * Generates public/sitemap.xml from prerender-routes.txt.
 *
 * The six public paths used to be written by hand in four places at once —
 * this file, prerender-routes.txt, app.routes.ts and SeoService — which is how
 * an apex/www mismatch ended up in the sitemap and nowhere else. The prerender
 * route list is already the build's source of truth, so the sitemap is derived
 * from it rather than maintained alongside it.
 *
 * lastmod comes from git history for each page's own template plus the two
 * i18n bundles (the i18n files are the actual visible copy, so a wording change
 * is a content change), never from the build clock — a timestamp that moves on
 * every deploy tells crawlers nothing.
 *
 * priority and changefreq are deliberately never emitted: Google has ignored
 * both for years. Omitting them here makes that permanent by construction.
 */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const root = __dirname + '/..';
const routesFile = path.join(root, 'prerender-routes.txt');
const constantsFile = path.join(root, 'src/app/shared/constants.ts');
const outFile = path.join(root, 'public/sitemap.xml');

const I18N = ['public/i18n/bg.json', 'public/i18n/en.json'];

/** Template(s) whose git history counts as a change to a given public path. */
const TEMPLATES = {
  '/': ['src/app/core/components/home/home.component.html', 'src/app/features/components/products-list/products-list.component.html'],
  '/menu': ['src/app/features/pages/menu-page/menu-page.component.html', 'src/app/features/components/menu-list/menu-list.component.html'],
  '/contacts': ['src/app/features/pages/contacts-page/contacts-page.component.html'],
};

/** One source of truth for the origin: the constant the app itself ships. */
function siteOrigin() {
  const src = fs.readFileSync(constantsFile, 'utf8');
  const match = src.match(/SITE_ORIGIN\s*=\s*'([^']+)'/);
  if (!match) {
    console.error('\n✖ Could not read SITE_ORIGIN from src/app/shared/constants.ts\n');
    process.exit(1);
  }
  return match[1].replace(/\/+$/, '');
}

function lastmod(bgPath) {
  const files = (TEMPLATES[bgPath] || []).concat(I18N).filter((f) => fs.existsSync(path.join(root, f)));
  try {
    const iso = execFileSync('git', ['log', '-1', '--format=%cI', '--'].concat(files), {
      cwd: root,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    if (iso) return iso.slice(0, 10);
  } catch {
    // Shallow checkout or no git — fall through.
  }
  return new Date().toISOString().slice(0, 10);
}

const origin = siteOrigin();
const routes = fs
  .readFileSync(routesFile, 'utf8')
  .split('\n')
  .map((line) => line.trim())
  .filter(Boolean);

// Bulgarian lives at the root, English under /en. Pair them so each URL can
// list every language version of itself, including itself, which is what
// Google requires of hreflang annotations.
const bgRoutes = routes.filter((r) => !r.startsWith('/en'));
const enOf = (bg) => (bg === '/' ? '/en' : `/en${bg}`);

const missing = bgRoutes.map(enOf).filter((en) => !routes.includes(en));
if (missing.length) {
  console.error(`\n✖ prerender-routes.txt is missing the English counterpart(s): ${missing.join(', ')}\n`);
  process.exit(1);
}

const url = (p) => origin + (p === '/' ? '/' : p);

const entries = [];
for (const bg of bgRoutes) {
  const stamp = lastmod(bg);
  for (const p of [bg, enOf(bg)]) {
    entries.push(
      [
        '  <url>',
        `    <loc>${url(p)}</loc>`,
        `    <lastmod>${stamp}</lastmod>`,
        `    <xhtml:link rel="alternate" hreflang="bg" href="${url(bg)}" />`,
        `    <xhtml:link rel="alternate" hreflang="en" href="${url(enOf(bg))}" />`,
        `    <xhtml:link rel="alternate" hreflang="x-default" href="${url(bg)}" />`,
        '  </url>',
      ].join('\n')
    );
  }
}

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by scripts/generate-sitemap.js from prerender-routes.txt.
  Do not edit by hand; add the route there and rebuild.
-->
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml"
>
${entries.join('\n')}
</urlset>
`;

fs.writeFileSync(outFile, xml);
console.log(`✅ sitemap.xml generated: ${entries.length} URLs on ${origin}`);
